/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.baidu.usercenter.api;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PasswordException extends org.apache.avro.specific.SpecificExceptionBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"error\",\"name\":\"PasswordException\",\"namespace\":\"com.baidu.usercenter.api\",\"fields\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  public PasswordException() {
    super();
  }
  
  public PasswordException(Object value) {
    super(value);
  }

  public PasswordException(Throwable cause) {
    super(cause);
  }

  public PasswordException(Object value, Throwable cause) {
    super(value, cause);
  }
  
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /** Creates a new PasswordException RecordBuilder */
  public static com.baidu.usercenter.api.PasswordException.Builder newBuilder() {
    return new com.baidu.usercenter.api.PasswordException.Builder();
  }
  
  /** Creates a new PasswordException RecordBuilder by copying an existing Builder */
  public static com.baidu.usercenter.api.PasswordException.Builder newBuilder(com.baidu.usercenter.api.PasswordException.Builder other) {
    return new com.baidu.usercenter.api.PasswordException.Builder(other);
  }
  
  /** Creates a new PasswordException RecordBuilder by copying an existing PasswordException instance */
  public static com.baidu.usercenter.api.PasswordException.Builder newBuilder(com.baidu.usercenter.api.PasswordException other) {
    return new com.baidu.usercenter.api.PasswordException.Builder(other);
  }
  
  /**
   * RecordBuilder for PasswordException instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificErrorBuilderBase<PasswordException>
    implements org.apache.avro.data.ErrorBuilder<PasswordException> {


    /** Creates a new Builder */
    private Builder() {
      super(com.baidu.usercenter.api.PasswordException.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.baidu.usercenter.api.PasswordException.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing PasswordException instance */
    private Builder(com.baidu.usercenter.api.PasswordException other) {
      super(other);
    }

    @Override
    public com.baidu.usercenter.api.PasswordException.Builder setValue(Object value) {
      super.setValue(value);
      return this;
    }
    
    @Override
    public com.baidu.usercenter.api.PasswordException.Builder clearValue() {
      super.clearValue();
      return this;
    }

    @Override
    public com.baidu.usercenter.api.PasswordException.Builder setCause(Throwable cause) {
      super.setCause(cause);
      return this;
    }
    
    @Override
    public com.baidu.usercenter.api.PasswordException.Builder clearCause() {
      super.clearCause();
      return this;
    }

    @Override
    public PasswordException build() {
      try {
        PasswordException record = new PasswordException(getValue(), getCause());
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
